### ISSUE TITLE
`cellsol` and `celllsol`

### ISSUE THREAD

**Issue by seguri** [RbtsEvrwhr-Riley/CellSol#12]
Hi,

Is this intentional?

<img width="414" alt="image" src="https://user-images.githubusercontent.com/2405157/157260757-5e779250-57e1-4a0f-9dd5-b1ff3a784853.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/2405157/157260859-f44cead7-92d1-45e5-83f5-0a923ba4dc82.png">

**Comment by RbtsEvrwhr-Riley** [comment]
No, no it is not. Fix coming in.
